services:
  - type: web
    name: ondeD
    runtime: php
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
